# Generated by Django 4.2.6 on 2023-11-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_alter_jurnal_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
